name: GitHub Deploy
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Deploy to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/Specshell -Dtoken=$GITHUB_TOKEN
