name: import-gpg

on:
  push:
    branches:
    - mavenCentral

jobs:
  import-gpg:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "specshell",
              "username": "${env.NEXUS_USER}",
              "password": "${env.NEXUS_PASSWORD}"
            }]

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Maven Verify
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn -B -V --no-transfer-progress verify -P sign \
          --define gpg.keyname=${{ steps.import_gpg.outputs.fingerprint }} \
          --define gpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
