name: Release workflow
on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: specshell
        server-username: NEXUS_USER
        server-password: NEXUS_PASSWORD

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Configure git
      run: |
        git config --global committer.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global committer.name "GitHub Actions"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Checkout main branch
      run: git checkout main

    - name: Maven Install
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn -B -V --no-transfer-progress --file pom.xml install

    - name: Set Version
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "RELEASE_VERSION=${version%-SNAPSHOT}" >> $GITHUB_ENV

    - name: Perform release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn -B -V --no-transfer-progress --file pom.xml release:prepare release:perform

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.RELEASE_VERSION }}
        release_name: v${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
