name: Release workflow
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "specshell",
                "username": "${env.NEXUS_USER}",
                "password": "${env.NEXUS_PASSWORD}"
            }]

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Get Version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "GIT_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Set version
      run: |
        mvn versions:set -DnewVersion=$RELEASE_VERSION

    - name: Deploy Nexus release
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        mvn -B -V --no-transfer-progress deploy

    - name: Deploy GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -B -V --no-transfer-progress deploy \
          -P github \
          --define github.repo=specshell.software.maven.pom
