name: Release workflow
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "specshell",
                "username": "${env.NEXUS_USER}",
                "password": "${env.NEXUS_PASSWORD}"
            }]

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Get Version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "GIT_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Set version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        mvn versions:set -DnewVersion=$RELEASE_VERSION

    - name: Deploy Nexus release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        mvn -B -V --no-transfer-progress --file pom.xml deploy

    - name: Deploy GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        mvn -B -V --no-transfer-progress --file pom.xml deploy -Dregistry=https://maven.pkg.github.com/Specshell -Dtoken=$GITHUB_TOKEN
